//! Raw FFI bindings to `libopenconnect`.
//!
//! Generated by `bindgen` at build time. See `build.rs`.
//! Consumers should prefer the safe wrapper in the `gp-tunnel` crate.
//!
//! On Windows (or when `libopenconnect-dev` is not installed), the bindings
//! are not generated and this crate is essentially empty.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

#[cfg(unix)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// --- Progress callback trampoline (csrc/progress_shim.c) ---
//
// libopenconnect's progress callback is variadic (printf-style). Rust on
// stable can't define variadic C functions, so we route through a small C
// trampoline that formats the message and calls a plain Rust sink.

#[cfg(unix)]
extern "C" {
    /// Variadic trampoline exported by `csrc/progress_shim.c`. Pass its
    /// address as the `progress` argument to `openconnect_vpninfo_new`.
    pub fn pangolin_progress_trampoline(
        privdata: *mut ::std::os::raw::c_void,
        level: ::std::os::raw::c_int,
        fmt: *const ::std::os::raw::c_char,
        ...
    );
}

/// Non-variadic Rust sink that the C trampoline forwards pre-formatted
/// progress messages to. Called from C, so `extern "C"` and `#[no_mangle]`.
///
/// Routes messages to `tracing` at a level inferred from libopenconnect's
/// `PRG_*` constants.
///
/// # Safety
/// `msg` must be a NUL-terminated C string or NULL. Callers (i.e. the C
/// trampoline in `csrc/progress_shim.c`) always pass a valid pointer from
/// `vsnprintf`. `privdata` is unused.
#[cfg(unix)]
#[no_mangle]
pub unsafe extern "C" fn pangolin_progress_sink(
    _privdata: *mut ::std::os::raw::c_void,
    level: ::std::os::raw::c_int,
    msg: *const ::std::os::raw::c_char,
) {
    if msg.is_null() {
        return;
    }
    let cstr = unsafe { std::ffi::CStr::from_ptr(msg) };
    let s = cstr.to_string_lossy();
    // PRG_ERR = 0, PRG_INFO = 1, PRG_DEBUG = 2, PRG_TRACE = 3
    match level {
        0 => tracing::error!(target: "openconnect", "{}", s),
        1 => tracing::info!(target: "openconnect", "{}", s),
        2 => tracing::debug!(target: "openconnect", "{}", s),
        _ => tracing::trace!(target: "openconnect", "{}", s),
    }
}
